In [1]:
# Ml Based stock price prediction & algo trading backtesting
# Importing the required libraries
import yfinance as yf
import numpy as np

data = yf.download('NESTLEIND.NS', start='2020-01-01')
data['returns'] = np.log(data.Close.pct_change()+1)

[*********************100%%**********************]  1 of 1 completed

In [2]:
data.head()

,Open,High,Low,Close,Adj Close,Volume,returns
Date,,,,,,,
2020-01-01,1481.900024,1484.935059,1471.224976,1477.905029,1409.473877,238590,NaN
2020-01-02,1484.890015,1485.295044,1468.714966,1472.935059,1404.734009,461160,-0.003369
2020-01-03,1475.000000,1479.500000,1455.609985,1459.359985,1391.787720,400000,-0.009259
2020-01-06,1454.199951,1454.199951,1427.500000,1441.665039,1374.911987,651360,-0.012199
2020-01-07,1442.354980,1454.675049,1426.084961,1429.074951,1362.904663,722370,-0.008771

In [3]:
data.tail()

,Open,High,Low,Close,Adj Close,Volume,returns
Date,,,,,,,
2024-05-06,2474.399902,2479.949951,2446.949951,2457.399902,2457.399902,715996,0.000529
2024-05-07,2469.000000,2528.350098,2459.550049,2508.649902,2508.649902,1073459,0.020641
2024-05-08,2502.449951,2548.000000,2485.649902,2539.000000,2539.000000,699070,0.012026
2024-05-09,2539.000000,2549.899902,2502.000000,2513.449951,2513.449951,702155,-0.010114
2024-05-10,2513.449951,2549.000000,2503.449951,2533.199951,2533.199951,697416,0.007827

In [4]:
# create a function to create lag returns based on the given return data
def lagit(data, lags):
    names = []
    for i in range(1, lags + 1):
        data['Lag_'+str(i)] = data['returns'].shift(i)
        names.append('Lag_'+str(i))
    return names

# create lagnames of your choice (demo: 5 day lags)
lagnames = lagit(data,5)
lagnames

['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']

In [5]:
## Drop missing values
data.dropna(inplace=True)

In [6]:
## print the dataframe (entire data)
data

,Open,High,Low,Close,Adj Close,Volume,returns,Lag_1,Lag_2,Lag_3,Lag_4,Lag_5
Date,,,,,,,,,,,,
2020-01-09,1449.500000,1467.500000,1445.000000,1464.344971,1396.541626,557080,0.017373,0.007008,-0.008771,-0.012199,-0.009259,-0.003369
2020-01-10,1464.344971,1471.890015,1457.025024,1468.584961,1400.585571,392740,0.002891,0.017373,0.007008,-0.008771,-0.012199,-0.009259
2020-01-13,1474.790039,1474.790039,1460.099976,1465.824951,1397.953247,269900,-0.001881,0.002891,0.017373,0.007008,-0.008771,-0.012199
2020-01-14,1465.790039,1489.500000,1460.699951,1486.859985,1418.014282,503780,0.014248,-0.001881,0.002891,0.017373,0.007008,-0.008771
2020-01-15,1482.800049,1495.000000,1471.885010,1486.020020,1417.213135,414680,-0.000565,0.014248,-0.001881,0.002891,0.017373,0.007008
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-06,2474.399902,2479.949951,2446.949951,2457.399902,2457.399902,715996,0.000529,-0.022624,0.001952,-0.000957,0.010836,-0.031675
2024-05-07,2469.000000,2528.350098,2459.550049,2508.649902,2508.649902,1073459,0.020641,0.000529,-0.022624,0.001952,-0.000957,0.010836
2024-05-08,2502.449951,2548.000000,2485.649902,2539.000000,2539.000000,699070,0.012026,0.020641,0.000529,-0.022624,0.001952,-0.000957
2024-05-09,2539.000000,2549.899902,2502.000000,2513.449951,2513.449951,702155,-0.010114,0.012026,0.020641,0.000529,-0.022624,0.001952
2024-05-10,2513.449951,2549.000000,2503.449951,2533.199951,2533.199951,697416,0.007827,-0.010114,0.012026,0.020641,0.000529,-0.022624

In [7]:
## Step-1: Define the X and Y variables
X = data[lagnames] 
Y = data['returns']

In [9]:
## Step-2: Split the data into TRAINING & TEST DATA
# import dependencies for machine learning data analysis
from sklearn.model_selection import train_test_split
## split the data into training and test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, shuffle=False, test_size = 0.3, random_state = 101)
X.shape, Y.shape, X_train.shape, X_test.shape, Y_train.shape,  Y_test.shape

((1073, 5), (1073,), (751, 5), (322, 5), (751,), (322,))

In [10]:
## Step-3: Define your regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
## Step-4: Fit the model / Estimate the parameters (a & bs) using the TRAINING data
model.fit(X_train,Y_train)
model.coef_

array([-0.07206249, -0.09278529,  0.09440921,  0.05828462,  0.07926946])

In [12]:
## define the regrssion model
model = LinearRegression()

In [13]:
Y_test

Date
2023-01-16   -0.002467
2023-01-17    0.010592
2023-01-18   -0.006156
2023-01-19   -0.007202
2023-01-20   -0.024746
                ...
2024-05-06    0.000529
2024-05-07    0.020641
2024-05-08    0.012026
2024-05-09   -0.010114
2024-05-10    0.007827
Name: returns, Length: 322, dtype: float64